In [1]:
import numpy as np

In [2]:
lst = []
n = int(input('Enter the number of elements you want in the list:'))
for i in range(0,n):
    ele = int(input())
    lst.append(ele)
#print(lst)
listArray = np.array(lst)
#print(listArray)
(unique,counts) = np.unique(listArray,return_counts = True)
frequencies = np.asarray((unique,counts)).T
print(frequencies)

Enter the number of elements you want in the list:4
1
2
2
1
[[1 2]
 [2 2]]


In [3]:
def shift(arr,n):
    count = 0
    for i in range(0,n):
        if(arr[i] == 1):
            count += 1
    for i in range(0,count):
        arr[i] = 1
    for i in range(count,n):
        arr[i] = 0
    arr = np.asarray(arr)
    print(arr)
arr = [1,0,1,0,0,1,1]
n = len(arr)
shift(arr,n)

[1 1 1 1 0 0 0]


In [4]:
def remove_char(str,n):
    first = str[:n]
    second = str[n+1:]
    return first + second
print(remove_char('Python', 0))
print(remove_char('Python', 3))
print(remove_char('Python', 5))

ython
Pyton
Pytho


In [5]:
mat = np.ones((3,3))
print(mat)
print()
mat = np.pad(mat,pad_width=1,mode='constant',constant_values=0)
print(mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
Array1 = np.array([0,10,20,40,60])
print('Array1: ',Array1)
Array2 = np.array([0,40])
print('Array2: ',Array2)
print('Comparison of each element: ')
print(np.in1d(Array1,Array2))

Array1:  [ 0 10 20 40 60]
Array2:  [ 0 40]
Comparison of each element: 
[ True False False  True False]


In [7]:
Array1 = np.array([0,10,20,40,60,80])
print('Array1: ',Array1)
Array2 = np.array([10,30,40,50,70])
print('Array2: ',Array2)
print('Exclusive OR of the two arrays: ')
print(np.setxor1d(Array1,Array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]
Exclusive OR of the two arrays: 
[ 0 20 30 50 60 70 80]


In [8]:
Array1 = np.array([0,10,20,40,60,80])
print('Array1: ',Array1)
Array2 = np.array([10,20,30,40,50,70])
print('Array2: ',Array2)
print("Vertical stack of the two arrays: ")
print(np.column_stack((Array1,Array2)))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 20 30 40 50 70]
Vertical stack of the two arrays: 
[[ 0 10]
 [10 20]
 [20 30]
 [40 40]
 [60 50]
 [80 70]]


In [9]:
r = int(input('Enter the number of rows: '))
c = int(input('Enter the number of columns: '))
matrix = []
print('Enter the entries rowwise')
for i in range(r):
    a = []
    for j in range(c):
        a.append(int(input()))
    matrix.append(a)
matrix = np.asmatrix(matrix)
print("The matrix is: ")
print(matrix)
print("The rank of the matrix is: ")
print(np.linalg.matrix_rank(matrix))
print("The trace of the matrix is: ")
print(np.trace(matrix))
print("The determinant of the matrix is: ")
print(np.linalg.det(matrix))

Enter the number of rows: 2
Enter the number of columns: 2
Enter the entries rowwise
1
2
3
4
The matrix is: 
[[1 2]
 [3 4]]
The rank of the matrix is: 
2
The trace of the matrix is: 
5
The determinant of the matrix is: 
-2.0000000000000004
